### ISSUE TITLE
ERROR  1146 : Table 'sbfspot.config' doesn't exist

### ISSUE THREAD

**Issue by danny12321** [SBFspot/sbfspot-config#1]
I Get this error message wheen I try to install and I don't know how to solve it. 

│There is a problem: 
│ ERROR 1146 (42S02) at line 1: Table 'sbfspot.config' doesn't exist

**Comment by sbf-** [comment]
When using MySQL, you have to create the SBFspot database and SBFspotUser manually.
I published V1.0.8 today. Retry the installation - it will fail again, but it will leave 2 .sql files in /usr/local/bin/sbfspot.3
I'll update the readme soon.

**Comment by danny12321** [comment]
Thank you, I don't have that problem anymore. But now I have the error 'Invalid timezone specified: UTC'. Do you know how I can set a valid timezone?

**Comment by sbf-** [comment]
Timezone must be set with `raspi-config` (Localization Options->Change Timezone)

**Comment by AJErazzor** [comment]
Getting the same error
 There is a problem:                                              
 ERROR 1146 (42S02) at line 1: Table 'sbfspot.config' doesn't exi
remote mySQL server - user and database created with script, however I added full permissions to user to see if this would help but no

**Comment by sbf-** [comment]
Running MySQL server on Linux?
If yes then it's probably a case sensitivity issue (SELECT * FROM SBFspot.Config)

**Comment by AJErazzor** [comment]
Yes Linux - will try changing table name and report back

Thanks
Andrew

**Comment by AJErazzor** [comment]
I ran a local copy and changed (SELECT * FROM SBFspot.config) to (SELECT * FROM Config)

Get past that but now getting:
/usr/local/bin/sbfspot.3/SBFspot: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/bin/sbfspot.3/SBFspot)
/usr/local/bin/sbfspot.3/SBFspot: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/bin/sbfspot.3/SBFspot)

**Comment by sbf-** [comment]
That's a bigger issue ;-)
What image is installed on your RPi?

**Comment by AJErazzor** [comment]
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian

**Comment by sbf-** [comment]
Good old Jessie ;-)
Only tested on Stretch.

**Comment by AJErazzor** [comment]
nope that didnt work - i have upgraded to Stretch and the changed case in the batch file works fine now - just have to work out the SetPlantTime returned an error: -1 issue now but nothing to do with this issue
