### ISSUE TITLE
Debian Buster for raspi

### ISSUE THREAD

**Issue by agricolaXIII** [SBFspot/sbfspot-config#10]
Hello,
last week I had upgradet to Debian Buster.
After the upgrade SBFSpot has damaged the system, so I must power of my raspian. I'd try that three times. Since I had disabled the SBFSpot exe file, the system run stable.
Tomorow I'd try to reinstall SBFSpot, and it's the same problem.
Is there a planning to upgrade SBFSpot for Debian Buster? Or is there a problem on my new Debian and the latest version is running on other Buster-Systems?

Greetings 
Jens

**Comment by sbf-** [comment]
For SBFspot there are no known issues.
For the upload daemon to PVO, there is this temporary [workaround](https://github.com/SBFspot/SBFspot/issues/295)

**Comment by deagel** [comment]
Hi,
is it possible to add the workaround to sbfspot-config inkl. a mariadb / mysql supported version?

thanks

dennis

**Comment by jvlerick** [comment]
After upgrading my system to buster SBFspot no longer reports anything to my Domoticz.
When testing with "/usr/local/bin/sbfspot.3/SBFspot -v -finq -nocsv" I get this error: "error while loading shared libraries: libboost_date_time.so.1.62.0: cannot open shared object file: No such file or directory". Apparently with upgrading to Buster libboost version is now 1.67. Is there any way to solve this?

**Comment by sbf-** [comment]
Fixed in V1.1.0
