### ISSUE TITLE
upload to MariaDB fails

### ISSUE THREAD

**Issue by khs1974** [SBFspot/sbfspot-config#11]
Hello,

I installed the latest SBFspot version on my Raspberry Pi 3 Model B Rev 1.2
I selected MariaDB and the installation was successfull.
However the datafiles (in the location /usr/local/bin/sbfspot.3) won´t update; the “last change date” is still the same as the date of installation and the file size doesn’t increase.
When I run the SBFspot installation again and select the existing configuration (/usr/local/bin/sbfspot.3/SBFspot.cfg), "SQlite" is pre-selected and not "MariaDB".
Previously I selected SQlite, but changed this later on.
What am I doing wrong?

Kees

**Comment by sbf-** [comment]
Can you post the output of sbfspot-config script?

**Comment by khs1974** [comment]
Hereby;

[19:51:22] openhabian@openhab:~$ sudo curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash
SBFspot Configuration Tool V1.0.14
Running on Raspberry Pi 3 Model B Rev 1.2
Checking whiptail... Installed.
architecture=armhf
Raspbian GNU/Linux 10 (buster)
username=openhabian
userhome=/home/openhabian
Minimum SBFspot version supported by this tool is 3.5.0
Request to install latest version (3.5.2)
Searching for existing configuration(s)...
Reading settings from /usr/local/bin/sbfspot.3/SBFspot.cfg
do_db_config:SBFspot
Saving defaults to /var/tmp/sbfspot.3/sbfspot.defaults... Done
Performing some checks before installation... Done
Downloading https://github.com/sbfspot/sbfspot/releases/download/V3.5.2/sbfspot-mysql-arm-linux.tar.gz
Copying files...
Checking database...
Schema Version=1
Configuring SBFspot... Done
Running SBFspot...
Creating cron jobs...

## SBFspot
*/5 6-22 * * * /usr/local/bin/sbfspot.3/daydata
55 05 * * * /usr/local/bin/sbfspot.3/monthdata
NetID=04
Removing temporary files...
Installation complete
[20:10:46] openhabian@openhab:~$

**Comment by khs1974** [comment]
and the file SBFspot.cfg: 

# SBFspot.cfg - Created Thu 26 Sep 2019 08:10:30 PM CEST with sbfspot-config V1.0.14
# For detailed configuration info, refer to SBFspot.default.cfg
#
BTAddress=00:80:25:A4:EE:57
MIS_Enabled=0
BTConnectRetries=15
Password=0000
Plantname=MyPlant
OutputPath=/home/openhabian/smadata/%Y
OutputPathEvents=/home/openhabian/smadata/%Y/Events
CSV_Export=1
CSV_ExtendedHeader=1
CSV_Header=1
CSV_SaveZeroPower=1
CSV_Delimiter=semicolon
CSV_Spot_TimeSource=inverter
CSV_Spot_WebboxHeader=0
Timezone=Europe/Amsterdam
Latitude=52.37
Longitude=4.90
Locale=en-US
DateTimeFormat=%d/%m/%Y %H:%M:%S
DateFormat=%d/%m/%Y
TimeFormat=%H:%M:%S
DecimalPoint=comma
CalculateMissingSpotValues=0
SQL_Database=SBFspot
SQL_Hostname=localhost
SQL_Username=SBFspotUser
SQL_Password=SBFspotPassword
# End of Config

**Comment by sbf-** [comment]
Looks OK to me...
What is the output of `/usr/local/bin/sbfspot.3/SBFspot -?`

**Comment by khs1974** [comment]
![SBFspot_printscreen](https://user-images.githubusercontent.com/55744403/66157308-ced7be00-e623-11e9-9741-b37548c7a1f7.JPG)

**Comment by khs1974** [comment]
the file "SBFspot" is not readable.

**Comment by sbf-** [comment]
is this OK now?

**Comment by khs1974** [comment]
No, I'm using SQlite at the moment because that does work..

**Comment by sbf-** [comment]
Can't reproduce issue
