### ISSUE TITLE
Lat/Long Configuration Error when starting with -

### ISSUE THREAD

**Issue by badger-github** [SBFspot/sbfspot-config#12]
Hi 
Just setting up a new system on PI Zero (Buster Lite)

I live in Western Australia and when trying to enter the Lat/Long the config program is giving the following error:

main: line 1354: set: -3: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]

This is when using (for example a Lat / Long for Perth (WA)) of -31.956027/115.860576

If I remove the - from the front it will accept the Lat / Long

Would this be an issue or am I doing something wrong?

Thank you for your time

Pete

**Comment by sbf-** [comment]
I'll have to check this.
