### ISSUE TITLE
error running sbfspot-config

### ISSUE THREAD

**Issue by howesij** [SBFspot/sbfspot-config#16]
Fails to get username

root@Nomads-Weather2:~# curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash
SBFspot Configuration Tool V1.0.15
Running on Raspberry Pi Zero W Rev 1.1
Checking whiptail... Installed.
architecture=armhf
Raspbian GNU/Linux 9.11 (stretch)
Failed to get username

**Comment by sbf-** [comment]
Don't login as root

**Comment by howesij** [comment]
Hi 
Thanks
Now getting error

Wed Jan 22 20:36:49 2020: CRITICAL: Logon failed. Check 'USER' Password
The inverter password has been changed
