### ISSUE TITLE
sbfspot-config will not install version 3.6.0

### ISSUE THREAD

**Issue by michaelsidenius** [SBFspot/sbfspot-config#19]
sbfspot-config can only find the 3.5.x versions.

line 392:`local rlist=($(grep -Po "(\d+\.)(\d+\.)(\d)/.*\.gz" "$tmppath/releases"))`

will not extract any 3.6.0 gz files

Apparently the version 3.6.0 does not have a subdirectory så it will not show up. This line will show it:
`local rlist=($(grep -Po "(\d+\.)(\d+\.)(\d).*\.gz" "$tmppath/releases"))`
Removed the `"/"`

**Comment by sbf-** [comment]
V3.6.0 doesn’t have any precompiled files yet, so it’s normal you don’t see it in the list.
See also #14

**Comment by sbf-** [comment]
Fixed in V1.1.0
