### ISSUE TITLE
device check returns not running on a PI

### ISSUE THREAD

**Issue by yustmenl** [SBFspot/sbfspot-config#20]
I tryed to run the SBFspot config but the script returns it's not running on a Raspberry.

when running cat /proc/device-tree/model it returns "Raspberry Pi 3 Model B rev 1.2"
so it defenetly is running on a Pi.

but when checking the /proc/cpuinfo file it's not showing anything with model name.
the closest thing i find for that is this line:
Model           : Raspberry Pi 3 Model B Rev 1.2

**Comment by yustmenl** [comment]
the output of dpkg --print-architecture is "armhf"

and "grep -a "Raspberry" /proc/device-tree/model" also works on my PI

**Comment by sbf-** [comment]
Thanks, I’ll fix it ASAP

**Comment by yustmenl** [comment]
Thanks it works!! now i will have to wait before my first data to become visable on PVoutput.
