### ISSUE TITLE
SBFspot docker MariaDB10

### ISSUE THREAD

**Issue by TerrorSource** [SBFspot/sbfspot-config#22]
Hi,

I'm trying to configure SBFspot in Docker to use MariaDB 10 on a Synology to save my data.
Exporting/importing in MariaDB 10 is much easier as using csv files or a single db file.
Docker image i'm using: https://github.com/nakla/sbfspot

SBFspot.cfg
``# MySQL
SQL_Database=sbfspot
SQL_Hostname=192.168.1.x
SQL_Username=SBFspotUser
SQL_Password=password``

Error via Terminal: 
``Error: Can't open MySQL db [sbfspot] : Can't connect to MySQL server on '192.168.1.x' (115)``

How do i get this working? that SBFspot puts the data in MariaDB 10

**Comment by sbf-** [comment]
This is explained [here](https://github.com/nakla/sbfspot#usage)
