### ISSUE TITLE
Can not define MQTT user and password

### ISSUE THREAD

**Issue by EddyBin** [SBFspot/sbfspot-config#27]
Try to install the MQTT component, but can not define user and password.
Manual adjustment of the  SBFspot.cfg with nano not possible as the file gives an error "File "SBFspot,cfg" is unwritable in nano

**Comment by EddyBin** [comment]
try to add the following to the interface at MQTT_PublisherArgs

-u username -P password -h {host} -t {topic} -m "{{message}}"

but "-u username -P password" disappears if I click <ok>

**Comment by sbf-** [comment]
> Manual adjustment of the SBFspot.cfg with nano not possible as the file gives an error "File "SBFspot,cfg" is unwritable in nano

SBFspot.cfg is read-only for user pi

```
sudo nano /usr/local/bin/SBFspot.cfg
```
