### ISSUE TITLE
Bluetooth is not configured correctly

### ISSUE THREAD

**Issue by zinker** [SBFspot/sbfspot-config#30]
My raspberry pi3 B+ is installed with buster but after running sbfspot-config I get the error "Bluetooth is not configured correctly!"

When I run in terminal hcitool scan , my raspberry find devices in my house

How can I solve this problem ?

regards

**Comment by sbf-** [comment]
You have to configure your BT address in sbfspot-config. Now it's address is 00:00:00:00:00:00

**Comment by zinker** [comment]
Was looking for a field to put it in, but its in the config itself.

thx for helping
