### ISSUE TITLE
When using sbfspot-config selecting bluetooth does not trigger the scan

### ISSUE THREAD

**Issue by Stan-Gobien** [SBFspot/sbfspot-config#33]
When I select Bluetooth in the dialogscreen it does not trigger any scan it immediately goes back and shows the address as 00:00:00:00:00.
I had to select speedwire, then go back and select bluetooth and then it did trigger the scan and I could select the intervert and see it's MAC.

System: Raspberry Pi4b with the default Raspberry-pi OS.

**Comment by sbf-** [comment]
Unable to reproduce this behaviour
