### ISSUE TITLE
Doesn't work on 64 bit Raspberry Pi OS

### ISSUE THREAD

**Issue by HandyHat** [SBFspot/sbfspot-config#35]
When running on the aarch64 version of Raspberry Pi OS, the script outputs `Error: Not running Raspbian` - this is because `lsb_release -si` returns `Debian` on this version.

**Comment by sbf-** [comment]
This is by design. Anyway, this setup contains precompiled 32 bit executables which won't run on your system.
You have to follow the manual comile route.
