### ISSUE TITLE
curl install 3.8.3 error

### ISSUE THREAD

**Issue by halfagascan** [SBFspot/sbfspot-config#39]
curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash -s 3.8.3
SBFspot Configuration Tool V1.2.0
Running on Raspberry Pi 3 Model B Rev 1.2
Checking whiptail... Installed.
architecture=armhf
Raspbian GNU/Linux 11 (bullseye)
username=pi
userhome=/home/pi
Minimum SBFspot version supported by this tool is 3.5.0
Request to install version 3.8.3
Version 3.8.3 is not available for installation.
Select one of (empty)
curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config | sudo bash -s 3.5.2
not available
Any method to install to bullseye?

**Comment by halfagascan** [comment]
The script works fine on buster install

**Comment by sbf-** [comment]
I´m working on bullseye image. Will be ready soon.

**Comment by halfagascan** [comment]
ok, thanks

**Comment by sbf-** [comment]
Bullseye images added to latest release
