### ISSUE TITLE
Error with mismatched SIDS and S/N when configuring new system for PVOutput

### ISSUE THREAD

**Issue by mynattryan** [SBFspot/sbfspot-config#46]
I'm attempting to configure SBFspot with two inverters (SMA SB7.0 and SB7.7) to automatically upload to PVOutput.org. I have two separate SIDs since there are two inverters, but when doing the initial sbfspot-config install, I get an error "Different number of SID/Serial" - it appears to not be getting the serials from the inverters. However running SBFspot by hand returns serial numbers and data from both inverters. I've attached logs from sbfspot-config and SBFspot for reference. Any suggestions? Thanks!

[sbfspot-config.log](https://github.com/SBFspot/SBFspot/files/8920925/sbfspot-config.log)
[SBFspot.log](https://github.com/SBFspot/SBFspot/files/8920926/SBFspot.log)

**Comment by sbf-** [comment]
Fixed in V1.3.0 (ec5f277)
