### ISSUE TITLE
Fresh install: SBFspotUpload installation failed: Different number of SID/Serial  

### ISSUE THREAD

**Issue by broke23** [SBFspot/sbfspot-config#47]
Hello again,

sbfspot at my parents' home went bust, corrupted card, so after +2years I had the chance to reinstall to latest version of SBF and raspian...

latest release installed on pi, boots, set up of SBFspot always results in **different number of SID/Serial...**

my parents have 3 inverters, all are seen by bluetooth, and are selected by default:

```
[*] 00:80:25:1F:71:E2  SMA002d 10 MIDDEN SN: 2120093240 SN2120093240
[*] 00:80:25:1D:5B:9C  SMA002d 10 VOOR SN: 2120102129 SN2120102129
[*] 00:80:25:1D:5B:96  SMA002d 12 ACHTER SN: 2120102179 SN2120102179 
```

I enabled MIS as proposed

the ID's at pvoutput: [49273](https://pvoutput.org/intraday.jsp?sid=49273), [49274 ](https://pvoutput.org/intraday.jsp?sid=49274)and [49275 ](https://pvoutput.org/intraday.jsp?sid=49275)(sums up on [49259 ](https://pvoutput.org/intraday.jsp?sid=49259)to have global overview instead of per inverter)

what I tried: 49259: not ok
49273 till 49275: not ok

when I abort: 

```
SBFspot Configuration Tool V1.2.1
Running on Raspberry Pi 2 Model B Rev 1.1
Checking whiptail... Installed.
architecture=armhf
Raspbian GNU/Linux 11 (bullseye)
username=pi
userhome=/home/pi
Minimum SBFspot version supported by this tool is 3.5.0
Request to install latest version (3.9.5)
Searching for existing configuration(s)...
Reading defaults from /var/tmp/sbfspot.3/sbfspot.defaults... Done
Scanning for Bluetooth devices, please wait...
Scanning for Bluetooth devices, please wait...
Saving defaults to /var/tmp/sbfspot.3/sbfspot.defaults... Done
Performing some checks before installation... Done
Downloading https://github.com/sbfspot/sbfspot/releases/download/V3.9.5/sbfspot-sqlite-arm-linux-bullseye.tar.gz
Copying files...
SBFspot.db exists
Checking database...
Schema Version=1
Saving existing SBFspot.cfg... Done
Configuring SBFspot... Done
Running SBFspot...
Creating cron jobs...

## SBFspot
*/5 6-22 * * * /usr/local/bin/sbfspot.3/daydata
55 05 * * * /usr/local/bin/sbfspot.3/monthdata
NetID=02
PVO enabled, configuring upload daemon...
Device Serial(s):
Not replacing daemon (unchanged)
**Different number of SID/Serial
Found 1 SIDS
Found 0 S/N**
```
tried the old ways:

SN2120102129:49273,SN2120093240:49274,SN2120102179:49275 (add the part SN before each serial)

2120102129:49273,2120093240:49274,2120102179:49275 (without SN part)

the api is ok, manually checked after copy paste ... 

What am I missing here you think ?

**Comment by sbf-** [comment]
Fixed in V1.3.0 (ec5f277)
