### ISSUE TITLE
ISSUE installing after firmware upgrade of Raspberry - Debian 11 - Bullseye 64bit

### ISSUE THREAD

**Issue by geurtsd** [SBFspot/sbfspot-config#52]
Hi,

After running a cleanup-install and upgrading the firmware of the Raspberry, the install scritp no longer works.
- upgrade with command: 
```
sudo rpi-update
```

It seems that with teh new firmware the output of the command 
```
lsb_release -si
```
no longer gives back "Raspbian", but it defaults to the standard "Debian".

I have tested the install script by modifying this line in your install script, and it installs, yet is not able to run SBFspot afterwards.
it gives error:

> pi@SolarLogger:/ $ sudo bash script
>SBFspot Configuration Tool V1.2.1
>Running on Raspberry Pi 3 Model B Rev 1.2
>Checking whiptail... Installed.
>architecture=arm64
>Debian GNU/Linux 11 (bullseye)
>username=pi
>userhome=/home/pi
>Minimum SBFspot version supported by this tool is 3.5.0
>Request to install latest version (3.9.3)
>Searching for existing configuration(s)...
>Reading settings from /usr/local/bin/sbfspot.3/SBFspot.cfg
>Saving defaults to /var/tmp/sbfspot.3/sbfspot.defaults... Done
>Performing some checks before installation... Done
>Downloading https://github.com/sbfspot/sbfspot/releases/download/V3.9.3/sbfspot-sqlite-arm-linux-bullseye.tar.gz
>Copying files...
>SBFspot.db exists
>Checking database...
>Schema Version=1
>Saving existing SBFspot.cfg... Done
>Configuring SBFspot... Done
>Running SBFspot...
>script: line 1322: /usr/local/bin/sbfspot.3/SBFspot: No such file or directory
>
>Installation aborted

However the listed install directory is present and there is the binary file "SBFspot".... (it shows up with "ls")
>pi@SolarLogger:/usr/local/bin/sbfspot.3 $ ls
>date_time_zonespec.csv  monthdata  SBFspot.cfg                  SBFspot.cfg.20220311_141416  TagListEN-US.txt  TagListFR-FR.txt  TagListNL-NL.txt
>daydata                 SBFspot    SBFspot.cfg.20220311_134058  TagListDE-DE.txt             TagListES-ES.txt  TagListIT-IT.txt
>pi@SolarLogger:/usr/local/bin/sbfspot.3 $

Manually running the file gives error:
>pi@SolarLogger:/usr/local/bin/sbfspot.3 $ SBFspot -v
> -bash: SBFspot: command not found

any ideas? compatability issue?

**Comment by sbf-** [comment]
Fixed in V1.3.0 (ec5f277)
