### ISSUE TITLE
 Unable to get list of available SBFspot versions for 'bookworm'

### ISSUE THREAD

**Issue by wil76** [SBFspot/sbfspot-config#67]
now I have created a new environment with Debian 12 I'm running into this issue.
how can I bypass this.
I assume, that the current version will run on bookworm

**Comment by sbf-** [comment]
Unfortunately the cross compilation toolchain is not yet available for "bookworm" so I can't build the images.
In the meantime you can follow the manual installation guide [here](https://github.com/SBFspot/SBFspot/wiki/Installation-Linux-SQLite#%EF%B8%8F-installation)

**Comment by jogi19** [comment]
Is there also a guide for manual installation using mysql ? I can not find it.

**Comment by sbf-** [comment]
V3.9.7 updated for bookworm

⚠️ New installation command:
`sudo bash -c "$(curl -s https://raw.githubusercontent.com/sbfspot/sbfspot-config/master/sbfspot-config)"`
