### ISSUE TITLE
BT Scan does not work with the installation script

### ISSUE THREAD

**Issue by shadowbyte68** [SBFspot/sbfspot-config#77]
Hello, I have set up an RPi3B+ V1.3 with Bookworm. No Bluetooth device is found using the installation script. BT is activated and is also recognized "sudo bluetoothctl". With “scan on” devices in the area are also detected. What possible solutions are there?

**Comment by shadowbyte68** [comment]
"hcitool scan" don't work...

>  while [ -z "$mac" ]; do
        echo Scanning for Bluetooth devices, please wait...
        IFS=
        local scanres
        scanres=$(hcitool scan)
        #scanres=$'Scanning...\n\t00:77:1A:2B:00:80\tThis is not an inverter\n'
        #scanres=$'Scanning...\n\t00:80:25:15:D3:E7\tBlueCN (STOLLMANN)\n\t00:15:BB:2B:3C:4D\tAnother SMA inverter\n\t00:77:1A:2B:00:80\tThis is not an inverter\n'
        #scanres=$'Scanning...\n'

**Comment by sbf-** [comment]
Do you find your inverter with `hcitool scan` ?

**Comment by shadowbyte68** [comment]
Hello, no see #2

**Comment by shadowbyte68** [comment]
Hello again, sorry, I solved the problem. The internal BT module of the RPi3B+ doesn't seem to be that powerful. I placed the RPi directly near the WR, now hcitool scan also shows the WR. But maybe this will help someone with troubleshooting, thank you
