### ISSUE TITLE
 /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9'  missing

### ISSUE THREAD

**Issue by yfands** [SBFspot/sbfspot-config#9]
Raspberry pi 3
Linux DomoticzPi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian

Error:
 /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9'  not found
 /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

**Comment by sbf-** [comment]
Not compatible with Jessie.

**Comment by sbf-** [comment]
See also https://github.com/SBFspot/SBFspot/issues/260
